/**
 * Phase 15 — real-document failure taxonomy.
 * Maps pipeline codes onto lab codes. Does not invent OCR results.
 */

import { OCR_ERROR } from '../phase14/errorTaxonomy.ts';

export const LAB_FAILURE = Object.freeze({
  WRONG_DOCUMENT_TYPE: 'WRONG_DOCUMENT_TYPE',
  WRONG_FIELD_MAPPING: 'WRONG_FIELD_MAPPING',
  CURRENCY_AS_IDENTIFIER: 'CURRENCY_AS_IDENTIFIER',
  DATE_AS_IDENTIFIER: 'DATE_AS_IDENTIFIER',
  IDENTIFIER_AS_AMOUNT: 'IDENTIFIER_AS_AMOUNT',
  PROVIDER_DISAGREEMENT: 'PROVIDER_DISAGREEMENT',
  LOW_IMAGE_QUALITY: 'LOW_IMAGE_QUALITY',
  PARTIAL_DOCUMENT: 'PARTIAL_DOCUMENT',
  ASSET_IDENTITY_CONFLICT: 'ASSET_IDENTITY_CONFLICT',
  MISSING_REQUIRED_FIELD: 'MISSING_REQUIRED_FIELD',
  NORMALIZATION_FAILURE: 'NORMALIZATION_FAILURE',
  LEARNING_MISLEAD: 'LEARNING_MISLEAD',
  CROSS_FIELD_CONFLICT: 'CROSS_FIELD_CONFLICT',
  DOCUMENT_TYPE_UNCERTAIN: 'DOCUMENT_TYPE_UNCERTAIN',
} as const);

export type LabFailureCode = (typeof LAB_FAILURE)[keyof typeof LAB_FAILURE];

const PIPELINE_TO_LAB: Record<string, LabFailureCode> = {
  [OCR_ERROR.OCR_CURRENCY_AS_IDENTIFIER]: LAB_FAILURE.CURRENCY_AS_IDENTIFIER,
  [OCR_ERROR.OCR_IDENTIFIER_AS_AMOUNT]: LAB_FAILURE.IDENTIFIER_AS_AMOUNT,
  [OCR_ERROR.OCR_PROVIDER_DISAGREEMENT]: LAB_FAILURE.PROVIDER_DISAGREEMENT,
  [OCR_ERROR.OCR_IMAGE_QUALITY_LOW]: LAB_FAILURE.LOW_IMAGE_QUALITY,
  [OCR_ERROR.OCR_DOCUMENT_CROPPED]: LAB_FAILURE.PARTIAL_DOCUMENT,
  [OCR_ERROR.OCR_ASSET_MATCH_CONFLICT]: LAB_FAILURE.ASSET_IDENTITY_CONFLICT,
  [OCR_ERROR.OCR_FIELD_NOT_FOUND]: LAB_FAILURE.MISSING_REQUIRED_FIELD,
  [OCR_ERROR.OCR_FIELD_TYPE_MISMATCH]: LAB_FAILURE.WRONG_FIELD_MAPPING,
  [OCR_ERROR.OCR_DATE_RELATIONSHIP_INVALID]: LAB_FAILURE.CROSS_FIELD_CONFLICT,
  [OCR_ERROR.OCR_TOTAL_MISMATCH]: LAB_FAILURE.CROSS_FIELD_CONFLICT,
  [OCR_ERROR.OCR_DOCUMENT_UNKNOWN]: LAB_FAILURE.WRONG_DOCUMENT_TYPE,
  OCR_DOCUMENT_TYPE_UNCERTAIN: LAB_FAILURE.DOCUMENT_TYPE_UNCERTAIN,
};

export function mapPipelineCode(code: string | null | undefined): LabFailureCode | null {
  if (!code) return null;
  return PIPELINE_TO_LAB[String(code)] || null;
}

export function mapPipelineCodes(codes: string[] = []): LabFailureCode[] {
  return [...new Set(codes.map((c) => mapPipelineCode(c)).filter(Boolean))] as LabFailureCode[];
}
